#!/usr/bin/python3
# SPDX-FileCopyrightText: 2026 misujumpei
# SPDX-License-Identifier: BSD-3-Clause

import sys  # sysモジュールを読み込み
import math #数学用モジュール

# print(sys.argv) # 確認済みのためコメントアウト



if len(sys.argv) >= 3:
    func = sys.argv[1]
    angle_deg = float(sys.argv[2])   # 文字列の '90' を、計算できる数値に変換

    angle_rad = math.radians(angle_deg)  # 角度をラジアンに変換

    if func == "sin":
        print(math.sin(angle_rad))
    elif func == "cos":
        print(math.cos(angle_rad))
    elif func == "tan":
        print(math.tan(angle_rad))
    else:
        print(f"エラー: {func} は未対応です")  #　上記3点以外の対応していない文字などを入力された際のクラッシュ防止

    
